### ISSUE TITLE
Code Group Icon

### ISSUE THREAD

**Issue by skyraah** [CrychicTeam/CrychicDoc#18]

**Comment by skyraah** [comment]
为代码组增加不同语言的图标支持

**Comment by skyraah** [comment]
- [ ] npm
- [ ] yarn
- [ ] KubeJS
- [ ] mcmeta
- [ ] md
- [ ] git

**Comment by M1hono** [comment]
https://vitepress.yiov.top/plugin.html#%E4%BB%A3%E7%A0%81%E7%BB%84%E5%9B%BE%E6%A0%87

**Comment by M1hono** [comment]
Finish.
