### ISSUE TITLE
网页开发疑问

### ISSUE THREAD

**Issue by Wulian233** [CrychicTeam/CrychicDoc#31]
您好！我对这个网站的图片查看插件很感兴趣，在我的网站里https://github.com/Wulian233/vmct-cn.top 使用的是medium-zoom，但是只能查看放大图片，而本站拥有更多功能，比如旋转等操作。请问这是用的什么库呢，感谢！

（我有个熟人fork了这个仓库，然后我点进来一看有点眼熟，readme原来参考了我写的，于是发现了这个宝藏项目）

**Comment by M1hono** [comment]
哈哈，参考的事被发现了，非常喜欢您的Readme就偷偷学习了一下希望您别介意。
图片查看是参考了[这个博客](https://justin3go.com/en/posts/2023/09/29vitepress%E4%B8%AD%E5%BC%95%E5%85%A5Tdesign%E5%B9%B6%E5%85%A8%E5%B1%80%E5%A2%9E%E5%8A%A0%E5%A4%A7%E5%9B%BE%E9%A2%84%E8%A7%88)然后做了一些改动让它能够添加黑名单。
组件的位置[在这](https://github.com/CrychicTeam/CrychicDoc/blob/main/.vitepress/theme/components/imageViewer.vue)。

**Comment by M1hono** [comment]
有什么疑问可以直接在群里问我，我先关掉Issue了。👌
